import DashboardSidebar from "@/components/DashboardSidebar";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Teko, Roboto } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

const teko = Teko({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "KAR-ROT SHOP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={teko.className}>
        <Navbar />
        <div className="w-full h-full flex">
          <div className="w-[250px] p-2 gap-5 flex-col flex align-center pt-20 bg-gray-100">
            <DashboardSidebar />
          </div>
          <main className="w-full h-full bg-white">{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
